apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-ingress
  namespace: deepmd
  annotations:
    
    nginx.ingress.kubernetes.io/proxy-body-size: 80m
    
    
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hepatic-service
            port:
              number: 5000
