apiVersion: apps/v1

kind: Deployment
metadata:
  name: bleed-deployment
  namespace: deepmd-ml
spec:
  selector:
    matchLabels:
      app: bleed
  replicas: 1
  template:
    metadata:
      labels:
        app: bleed
    spec:
      volumes:
      - name: deepmd-storage-input
        hostPath:
          path: /tmp/deepmd/bleed/input
          type: DirectoryOrCreate
      - name: deepmd-storage-output
        hostPath:
          path: /tmp/deepmd/bleed/output
          type: DirectoryOrCreate

      containers:
      - name: bleed
      
        image: anilyerramasu/deepbleed
        
        ports:
          - containerPort: 5000
        imagePullPolicy: Always
        volumeMounts:
          - name: deepmd-storage-input
            mountPath: /home/input
          - name: deepmd-storage-output
            mountPath: /home/output
        

---
apiVersion: v1
kind: Service
metadata:
  name: bleed-service
  namespace: deepmd-ml
spec:
  ports:
  - port: 5000
    targetPort: 5000
    name: http
  selector:
    app: bleed
