apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  namespace: deepmd-pacs
  labels:
    io.kompose.service: orthanctoolsjs
  name: orthanctoolsjs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
